apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: jnlp
      image: limina/jnlp-alpine-docker:latest
      args: [ '\$(JENKINS_SECRET)', '\$(JENKINS_NAME)' ]
    - name: sapmachine
      image: docker.wdf.sap.corp:51277/build-agent/sapmachine:17.0.6-1
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: "/home/user/.m2"
          name: "volume-0"
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
    #        - name: notaryvolume
    #          mountPath: "/root/.docker/trust"
    - name: curl
      image: rancher/curlimages-curl
      command:
        - cat
      tty: true
    - name: kustomize
      image: fluxcd/kustomize-controller
      command:
        - cat
      tty: true

  volumes:
    - name: volume-0
      hostPath:
        path: /tmp/jenkins/.m2
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: "workspace-volume"
      emptyDir:
        medium: ""